xychart-beta
    title "ALL SERVICES DROP IN AUGUST (Red = Below Average)"
    x-axis [eJournals, Home, Portals, Contact, Database, AskLib, Reference, Catalogs, Education]
    y-axis "% Change from Average" -20 --> 10
    bar [-14, -10, -8, -8, -6, -5, -3, 2, 5]
    line [0, 0, 0, 0, 0, 0, 0, 0, 0]
