xychart-beta
    title "AUGUST WORKLOAD DROPS ACROSS ALL SERVICES (5-Year Analysis 2020-2025)"
    x-axis [eJournals, Home, Portals, Contact, Database, AskLib, Reference, Catalogs, Education]
    y-axis "% Below 5-Year Monthly Average" -20 --> 10
    bar [-14, -10, -8, -8, -6, -5, -3, 2, 5]
    line [0, 0, 0, 0, 0, 0, 0, 0, 0]
